.travis.yml, README.md
Update testing MIVisionX with travis
Readme updates
=> MIVisionX Travis CI

MIVisionX-setup.py
=> Setup script enhancement

README.md, apps/cloud_inference/README.md, model_compiler/README.md
=> Documentation upgrades

README.md
=> MIVisionX webpage updates

MIVisionX-setup.py, MIVisionX.sln, README.md, amd_openvx/README.md, amd_openvx/openvx/openvx.vcxproj, amd_openvx_extensions/README.md, amd_openvx_extensions/amd_loomsl/README.md, amd_openvx_extensions/amd_loomsl/vx_loomsl.vcxproj, amd_openvx_extensions/amd_opencv/README.md, amd_openvx_extensions/amd_opencv/vx_opencv.vcxproj, amd_openvx_extensions/amd_opencv/vx_opencv.vcxproj.filters, utilities/loom_shell/loom_shell.vcxproj, utilities/runcl/runcl.vcxproj, utilities/runvx/runvx.vcxproj
* MIVisionX SLN
* Build Instructions
=> MIVisionX for Windows 10

model_compiler/python/nnir_to_openvx.py
Bug fix to get argmax correctly from fp16 inference
=> add argmax output code for fp16

model_compiler/python/caffe_to_nnir.py, model_compiler/python/nnir.py, model_compiler/python/nnir_to_openvx.py
Model compiler update for multiple output support and yolov3
=> model compiler update for supporting yolov3

amd_openvx_extensions/amd_opencv/include/vx_ext_opencv.h, amd_openvx_extensions/amd_opencv/source/internal_vxNodes.cpp, amd_openvx_extensions/amd_opencv/vx_opencv.vcxproj, amd_openvx_extensions/amd_winml/include/vx_ext_winml.h, amd_openvx_extensions/amd_winml/packages.config, amd_openvx_extensions/amd_winml/source/internal_vxNodes.cpp, amd_openvx_extensions/amd_winml/vx_winml.vcxproj, amd_openvx_extensions/amd_winml/vx_winml.vcxproj.filters
* OpenVX Extensions C Function export Fix
=> OpenVX Extension Windows Export

amd_openvx_extensions/amd_nn/src/batch_normalization_layer.cpp, amd_openvx_extensions/amd_nn/src/concat_layer.cpp, amd_openvx_extensions/amd_nn/src/convolution_layer.cpp, amd_openvx_extensions/amd_nn/src/deconvolution_layer.cpp, amd_openvx_extensions/amd_nn/src/fully_connected_layer.cpp, amd_openvx_extensions/amd_nn/src/scale_layer.cpp, amd_openvx_extensions/amd_nn/src/slice_layer.cpp, amd_openvx_extensions/amd_nn/src/upsample_nearest_layer.cpp
Fixes the error for concat layer happened with validation as well as minor fixes for other layers.
=> fp16 bug fix for concat and other layers

.gitmodules, README.md, utilities/inference_generator/CMakeLists.txt
* NNEF Submodule is disabled.
* NNEF functionality will only be supported in model_comiler
=> Git Submodules Removed

model_compiler/python/onnx_to_nnir.py
=> Bug fix for onnx_to_nnir

README.md, docs/README.md, model_compiler/README.md, samples/README.md, utilities/README.md, utilities/runvx/runvx.cpp
* Verify Installation
* Samples
* Utils
* Model Compiler
=> Readme fix for 1.2.0

CMakeLists.txt, amd_openvx_extensions/amd_nn/CMakeLists.txt
=> MIVisionX 1.2.0

model_compiler/python/nnir.py, model_compiler/python/onnx_to_nnir.py
1. Support for flatten 
2. Fixes Reshape failure in version 1.3 models
=> Onnx support 

model_compiler/python/nnir_to_openvx.py
Fixed the bug in nnir_to_openvx.py that was causing the accuracy errors.
=> fixed bug with fp16 accuracy

amd_openvx/openvx/ago/ago_kernel_api.cpp, amd_openvx/openvx/ago/ago_util_opencl.cpp, apps/cloud_inference/server_app/infcom.h
=> Ubuntu 18.04 warnings fix

apps/cloud_inference/README.md, apps/cloud_inference/client_app/README.md, apps/cloud_inference/client_app/infcom.h, apps/cloud_inference/server_app/CMakeLists.txt, apps/cloud_inference/server_app/README.md, apps/cloud_inference/server_app/arguments.cpp, apps/cloud_inference/server_app/compiler.cpp, apps/cloud_inference/server_app/inference.cpp, apps/cloud_inference/server_app/profiler.cpp, apps/cloud_inference/server_app/profiler.h
=> Cloud Inference Fix

amd_openvx_extensions/amd_media/decoder.cpp
fix bug reported by @paveltc when running multiple decoder in hardware mode
=> fixed bug with multiple stream decoding in copy to output

amd_openvx_extensions/amd_nn/src/batch_normalization_layer.cpp, amd_openvx_extensions/amd_nn/src/convolution_layer.cpp, model_compiler/python/nnir.py, model_compiler/python/nnir_to_openvx.py
fix bug in convolution_layer for calling fusion api
added fusion mode support in nnir for leaky_relu
=> fix bug in CBA fusion and added fusion for leaky relu

model_compiler/python/nnir_to_openvx.py
bug fix for fp16 nnir_to_openvx.
Models: onnx - Alexnet, vgg19
Caffe-googlenet
=> bug fix for fp16 nnir_to_openvx

model_compiler/python/nnir.py
=> add prefix to names for local tensor

apps/README.md, apps/rali_unittests/CMakeLists.txt, apps/rali_unittests/README.md, apps/rali_unittests/rali_unittests.cpp
App for running rali-unittests. Added ability to save output images.
=> added utility specifically for running the rali-unittests

amd_openvx/openvx/ago/ago_util.cpp, amd_openvx_extensions/amd_nn/CMakeLists.txt, amd_openvx_extensions/amd_nn/include/vx_amd_nn.h, amd_openvx_extensions/amd_nn/src/cast_layer.cpp, amd_openvx_extensions/amd_nn/src/kernels.cpp, amd_openvx_extensions/amd_nn/src/kernels.h, model_compiler/python/nnef_to_nnir.py, model_compiler/python/nnir.py, model_compiler/python/nnir_to_openvx.py, model_compiler/python/onnx_to_nnir.py
- Adds cast layer
- Adds support for clip layer when max and min are float values
- Adds support for reshape layer to accept shape from local tensor
- Adds support for anntest.cpp to dump intermediate tensors
=> Mobilenet-v1 onnx model support

MIVisionX-setup.py, README.md
* Support for latest ROCm - 2.9
* Support for latest MIOpen - 2.1.0
* Release Notes updated
=> MIVisionX 1.5

apps/rali_performance_tests/CMakeLists.txt, apps/rali_performance_tests/README.md, apps/rali_performance_tests/rali_performance_tests.cpp
RALI performance test utility.
=> added RALI performance unit test utility

apps/rali_performance_tests/rali_performance_tests.cpp
fixed bug in rali performance utility.
=> added fixed rali performance utility code

model_compiler/python/nnir.py, model_compiler/python/nnir_to_openvx.py
fix for yolov3 upsample layer from caffe model
=> yolov3 model compiler fix

MIVisionX-setup.py
=> making setup script python 3 compatible

README.md, apps/README.md
=> MIVisionX 1.6 Release

amd_openvx_extensions/amd_nn/src/cast_layer.cpp, model_compiler/python/nnir.py
Adds support for attribute to = 1 (float32 to float32 casting)
=> updating cast layer to support ssd-mobilenet

README.md, amd_openvx_extensions/amd_winml/README.md
Readme updates to install proper pre-reqs & AMD drivers
=> MIVisionX for Windows

amd_openvx/openvx/ago/ago_platform.h, amd_openvx_extensions/amd_opencv/vx_opencv.vcxproj
=> Windows Build - Allow VS Upgrade

MIVisionX-setup.py
Setup upgraded to reinstall the deps and remove old installation.
=> MIVisionX Setup - Reinstall & Delete features added

MIVisionX-setup.py
=> turbo jpeg installation with MIVisionX-setup.py

amd_openvx/openvx/ago/ago_interface.cpp
=> fix for issue #265

toolkit/analysis_and_visualization/classification/generate-visualization.py
was causing error when no hierarchy file given
=> ADAT - bugfix

CMakeLists.txt, apps/bubble_pop/README.md, apps/cloud_inference/README.md, rali/README.md
=> Release 1.8 Fix

utilities/rali/rali_performance_tests/rali_performance_tests.cpp
@kiritigowda Please merge this. It only changes the rali performance tests utility, it doesn't touch any other code.
=> fixed bug in rali performance tests utility

MIVisionX-Lite.sln, amd_openvx/openvx/openvx.vcxproj, amd_openvx_extensions/amd_opencv/vx_opencv.vcxproj, utilities/runcl/runcl.vcxproj, utilities/runvx/runvx.vcxproj
OpenVX 1.0.1 Builds and runs on windows
=> MIVisionX Lite - Windows Fix

rali/rali_pybind/CMakeLists.txt
=> RALI Pybind - Fix Install

utilities/rali/rali_performance_tests/rali_performance_tests.cpp
Added shuffle option to rali_performance_tests. Doesn't affect any other code. @kiritigowda Please merge this PR when you get a chance.
=> added shuffle option to rali_performance_tests

MIVisionX-setup.py
ProtoBuf set to install 3.12.0, can be dynamically changed with --protobuf option
=> MIVisionX Setup - ProtoBuf 3.12.0 Support

model_compiler/python/nnir.py
reading from graph.nnir: Reads a list to find int/float values. Changed from looking for numerical digits to count(.) in floats.
=> nnir bug fix

model_compiler/python/caffe_to_nnir.py, model_compiler/python/nnef_to_nnir.py, model_compiler/python/nnir.py, model_compiler/python/nnir_to_clib.py, model_compiler/python/nnir_to_nnef.py, model_compiler/python/nnir_to_openvx.py, model_compiler/python/nnir_update.py, model_compiler/python/onnx_to_nnir.py
@paveltc This is the PR for which you need to run the smoke test
=> Fix for batch size > 1 for reshape/shape layers

rali/rali/include/tf_record_reader.h, rali/rali/source/tf_record_reader.cpp
=> fix build error with tot

apps/cloud_inference/client_app/README.md
-instructions on building annInferenceApp using qmake
=> Update on Cloud inference app readme file

MIVisionX-setup.py, README.md
* MIOpen - use MIOpenGEMM and OpenCL enabled
* Readme updates
=> 1.9.1 Updates

amd_openvx_extensions/amd_nn/CMakeLists.txt, amd_openvx_extensions/amd_nn/include/vx_amd_nn.h, amd_openvx_extensions/amd_nn/src/kernels.cpp, amd_openvx_extensions/amd_nn/src/kernels.h, amd_openvx_extensions/amd_nn/src/reduce_min.cpp, model_compiler/python/nnir.py, model_compiler/python/nnir_to_openvx.py, model_compiler/python/onnx_to_nnir.py
Layer and model compiler changes.
Test cases added as a PR to MIVisionX-tests
=> reduce min layer

README.md, amd_openvx/README.md, amd_openvx_extensions/amd_winml/README.md, apps/README.md, apps/cloud_inference/README.md, model_compiler/README.md, utilities/inference_generator/README.md
https://gpuopen-professionalcompute-libraries.github.io/MIVisionX/ - Website has errors reading the readme.md's
This PR fixes the .md to html translations.
=> MIVisionX Online Documentation Fix

MIVisionX-setup.py, README.md
PR #351 requires RPP 0.5 as the default version to build.
=> RPP Updates for PR #351

MIVisionX-setup.py, README.md
* Boost Install Updates
* Package install updates
=> MIVisionX Setup - Install Updates

MIVisionX-setup.py
=> setup boost fix

rali/rali/source/ring_buffer.cpp
release ring buffer to avoid memory leak
=> release ring buffer memory

CMakeLists.txt, amd_openvx/openvx/CMakeLists.txt, rali/rali/CMakeLists.txt
=> RALI - Fix missing lib failure

amd_openvx/openvx/ago/ago_haf_cpu_filter.cpp, amd_openvx/openvx/ago/ago_kernel_api.cpp, amd_openvx/openvx/ago/ago_util.cpp, amd_openvx/openvx/api/vx_api.cpp
* Possible overflow on the multiplication fix
=> OpenVX - fix overflow

amd_openvx/openvx/ago/ago_util_opencl.cpp, utilities/runcl/runcl.cpp, utilities/runvx/vxEngine.cpp
* MIVisionX Level 2 - OpenCL code gen overflow fix
=> Ubuntu 20.04 Support - OpenCL

.travis.yml
=> Travis - Comprehensive Testing

amd_openvx_extensions/amd_media/README.md
Basic readme file for amd_media
=> add README file for amd_media

README.md, amd_openvx_extensions/README.md, amd_openvx_extensions/amd_media/README.md
=> Media Ext - Fix and additions

amd_openvx/openvx/openvx.vcxproj, amd_openvx_extensions/amd_loomsl/kernels/lens_distortion_remap.cpp, amd_openvx_extensions/amd_loomsl/vx_loomsl.vcxproj, amd_openvx_extensions/amd_opencv/vx_opencv.vcxproj, amd_openvx_extensions/amd_winml/vx_winml.vcxproj, utilities/loom_shell/loom_shell.vcxproj, utilities/runcl/runcl.vcxproj, utilities/runvx/runvx.vcxproj
* Update to VS 2019
* Fix advanced warnings
=> windows updates - SLN Updates

CMakeLists.txt
* version update
* cleanup
* minor fixes
=> Package Updates

MIVisionX-setup.py
* CentOS Support
*  RHEL Support
=> Setup Script - RHEL Support

MIVisionX-setup.py
=> Setup - OpenCV with Display for RHEL

CMakeLists.txt, README.md, amd_openvx/README.md, amd_openvx_extensions/amd_opencv/README.md, amd_openvx_extensions/amd_rpp/README.md
* Version Update
* Minor Readme Updates
=> MIVisionX 1.9.6

README.md, tests/README.md, tests/neural_network_tests/README.md, tests/neural_network_tests/runNeuralNetworkTests.py, tests/vision_tests/runVisionTests.py
=> Test - updates

model_compiler/python/nnir.py, model_compiler/python/nnir_to_openvx.py
fixes bug [SWDEV-270422](http://ontrack-internal.amd.com/browse/SWDEV-270422) and [SWDEV-270424](http://ontrack-internal.amd.com/browse/SWDEV-270424)
Fixes #429
=> fixes FP16 bug(SWDEV-270422) & getbuffer errors(SWDEV-270424)

rali/rali/source/master_graph.cpp, rali/rali/source/rali_api_info.cpp, rali/rali_pybind/amd/rali/ops.py
Fixes the hang in image augmentation app. Also changed the python API to use original size as applicable.
=> fix for hang at the end for RALI app and training

.jenkins/common.groovy, .jenkins/precheckin.groovy
* Vision Tests CPU/GPU
* NN Tests
=> Jenkins - Test Fix

.jenkins/common.groovy, MIVisionX-setup.py, README.md, tests/library_tests/README.md, tests/library_tests/runLibraryTests.py
=> Test - Installation Check

.jenkins/common.groovy, tests/library_tests/runLibraryTests.py, tests/neural_network_tests/runNeuralNetworkTests.py, tests/vision_tests/runVisionTests.py
* Check Installation
* Save Artifacts
=> Jenkins - Artifacts

CMakeLists.txt, MIVisionX-setup.py
* MIOpen 2.9.0 Install
* MIOpen Setup - minimum
=> MIVisionX Setup Updates

.jenkins/common.groovy
* CentOS 7 Build Fix
* CentOS 8 Build Fix
=> Jenkins Updates

MIVisionX-setup.py
Updated turbojpeg for partial decoder
=> MIVisionX Setup - Turbo-JPEG update

.jenkins/common.groovy, MIVisionX-setup.py, tests/neural_network_tests/runNeuralNetworkTests.py
* Setup Updates - SLES Support
* Cleanup - Remove duplicate packages
* Updates - jenkins tests
=> 2.0 Updates

.jenkins/common.groovy, .travis.yml, README.md
* Jenkins - Run CTS for OpenVX 1.3
=> Jenkins - CPU/GPU 1.3 Conformance

MIVisionX-setup.py, README.md
=> VX_NN - MIOpen Version Update

MIVisionX-setup.py, README.md, tests/neural_network_tests/runNeuralNetworkTests.py
* RHEL 7/8 - Support for Setup
* NN Tests - Support for RHEL
=> RHEL - Support for setup and test

.jenkins/common.groovy
Save CTS logs to review results in artifacts
=> Jenkins - OpenVX Conformance Log

.jenkins/common.groovy, tests/vision_tests/runVisionTests.py
* Build HIP Packages
* Run HIP Backend Tests
* Save Performance
* Run HIP CTS for OpenVX 1.3
=> CI - HIP Support

rocAL/README.md, rocAL/rocAL_pybind/CMakeLists.txt, rocAL/rocAL_pybind/setup.py
Fix rocAL Pybind build issue.
Update rocAL README.md for TurboJpeg installation.
=> rocAL - Pybind build issue fix

apps/image_augmentation/image_augmentation.cpp, rocAL/rocAL/source/cifar10_data_reader.cpp, rocAL/rocAL_pybind/amd/rali/ops.py, rocAL/rocAL_pybind/amd/rali/types.py, rocAL/rocAL_pybind/rali_pybind.cpp, utilities/rali/rali_dataloader/rali_dataloader.cpp
Update cifar10 data loader with latest changes
=> rocAL - cifar10 reader update

MIVisionX-setup.py, README.md
OpenCV Install at `-DCMAKE_INSTALL_PREFIX=/usr/local`
=> Setup - OpenCV install prefix

rocAL/rocAL/include/randombboxcrop_reader.h, rocAL/rocAL/source/randombboxcrop_reader.cpp, rocAL/rocAL_pybind/amd/rali/ops.py
Random BBox crop reader code clean up
Change USER_GIVEN_SIZE to MAX_SIZE for COCO partial decoding
=> rocAL - Random BBox crop reader code clean up

MIVisionX-setup.py, README.md, docker/centos7/level-4.dockerfile, docker/centos8/level-4.dockerfile, docker/mivisionx-on-centos7.dockerfile, docker/mivisionx-on-centos8.dockerfile, docker/mivisionx-on-ubuntu18.dockerfile, docker/mivisionx-on-ubuntu20.dockerfile, docker/ubuntu18/level-4.dockerfile, docker/ubuntu18/level-5.dockerfile, docker/ubuntu20/level-4.dockerfile, docker/ubuntu20/level-5.dockerfile
=> Docker - Dockerfiles update

docker/pytorch/mivisionx-with-pytorch.dockerfile
* Latest PyTorch with ROCm Support with rocAL
use 
```
sudo docker build -f mivisionx-with-pytorch.dockerfile -t pytorch-mivisionx .
```
=> Docker - PyTorch Support

MIVisionX-setup.py, README.md, docker/mivisionx-on-ubuntu18.dockerfile, docker/mivisionx-on-ubuntu20.dockerfile, docker/ubuntu18/level-4.dockerfile, docker/ubuntu18/level-5.dockerfile, docker/ubuntu20/level-4.dockerfile, docker/ubuntu20/level-5.dockerfile
* NN setup Fix
* Docker Updates
=> Boost Updates - MIOpen Install Fix

docker/pytorch/mivisionx-with-pytorch.dockerfile
* Boost Static and Shared Updates
=> PyTorch Docker - Updates

amd_openvx/cmake/FindOpenCL.cmake
Using the right OpenCL .SO to verify version.
=> OpenCL Version - Fix

amd_openvx/openvx/ago/ago_kernel_list.cpp
Fix - Conditional jump on uninitialized value
=> VxMapRemapPatch - Fix

tests/vision_tests/runVisionTests.py
Removing GDF from CI temporarily to complete test cycle
=> CI - Failure Bypass

.jenkins/common.groovy
* Backend Build - HIP/OCL
* Tests - OCL + CPU
* Tests - HIP + CPU
=> CI Updates - Tests

MIVisionX-setup.py, README.md, docker/centos7/level-4.dockerfile, docker/centos8/level-4.dockerfile, docker/mivisionx-on-centos7.dockerfile, docker/mivisionx-on-centos8.dockerfile, docker/mivisionx-on-ubuntu18.dockerfile, docker/mivisionx-on-ubuntu20.dockerfile, docker/ubuntu18/level-4.dockerfile, docker/ubuntu18/level-5.dockerfile, docker/ubuntu20/level-4.dockerfile, docker/ubuntu20/level-5.dockerfile
=> Deps Update - Use Release Tag for ROCM-CMAKE

README.md
=> Readme - Updates

rocAL/rocAL_pybind/CMakeLists.txt
Links the finalized path for MIVisionX - Fix for Issue #565
=> rocAL_pybind - CMakeList: add finalized install path

apps/dg_test/annmodule.cpp, apps/mivisionx_openvx_classifier/include/caffeModels.h
1.3 header updates - add vx_compabilty.h
=> VX_NN - Issue #577 Fix

amd_openvx_extensions/amd_nn/src/activation_layer.cpp
Added HIP backend option for activation layer which uses MIOpen
=> added HIP backend for activation layer

amd_openvx/openvx/CMakeLists.txt, utilities/mv_deploy/CMakeLists.txt
Problem: Issue #583
Fix: absolute path used in CMakeLists replaced
=> MV_Deploy - Fix absolute path

amd_openvx/openvx/ago/ago_haf_gpu_conversion.cpp, amd_openvx/openvx/hipvx/color_kernels.cpp
@asalmanp Fixes RGBX to NV12 and IYUV for both GPU backends
=> GPU OCL&HIP Backend - Color Convert Bug Fix

.jenkins/common.groovy
* CTS Logs saved for all platforms
=> CI:Jenkins - OpenVX 1.3 CTS Artifacts

docker/centos7/level-1.dockerfile, docker/centos7/level-2.dockerfile, docker/centos7/level-3.dockerfile, docker/centos7/level-4.dockerfile, docker/centos8/level-1.dockerfile, docker/centos8/level-2.dockerfile, docker/centos8/level-3.dockerfile, docker/centos8/level-4.dockerfile, docker/mivisionx-on-centos7.dockerfile, docker/mivisionx-on-centos8.dockerfile, docker/mivisionx-on-ubuntu18.dockerfile, docker/mivisionx-on-ubuntu20.dockerfile, docker/ubuntu18/level-1.dockerfile, docker/ubuntu18/level-2.dockerfile, docker/ubuntu18/level-3.dockerfile, docker/ubuntu18/level-4.dockerfile, docker/ubuntu18/level-5.dockerfile, docker/ubuntu20/level-1.dockerfile, docker/ubuntu20/level-2.dockerfile, docker/ubuntu20/level-3.dockerfile, docker/ubuntu20/level-4.dockerfile, docker/ubuntu20/level-5.dockerfile
* CentOS 7 - BugFix
* CentOS 8 - Updates
* Ubuntu 18 - Updates 
* Ubuntu 20 - Updates
HIP dependency - Python3 added to Level-2
=> Docker - Updates & Bug Fix

.jenkins/common.groovy, MIVisionX-setup.py
* Setup auto-install on SLES
* CI SLES Updates
=> SLES Support - Setup & CI

.jenkins/common.groovy, MIVisionX-setup.py, README.md
* Back-end - OCL & HIP
* SLES Updates
* Enhancements
=> Setup - Updates

.jenkins/common.groovy, CMakeLists.txt, amd_openvx/openvx/CMakeLists.txt
=> Issue #585: VX_NN - Link With MIOpen & MIOpenGEMM -- Fix

amd_openvx/openvx/hipvx/color_kernels.cpp
@asalmanp Turns out didn't need any changes to load routine itself, but had to restrict the loads within dstWidth and dstHeight
=> OpenVX HIP backend - bug fix - RGB to YUV4 &RGBX to YUV4

amd_openvx/openvx/hipvx/vision_kernels.cpp
@asalmanp Made changes to match OpenCL kernel
=> OpenVX 1.3 - HIP Backend - Harris Corner Bug Fix

docker/mivisionx-on-ubuntu18.dockerfile, docker/mivisionx-on-ubuntu20.dockerfile, docker/ubuntu18/level-2.dockerfile, docker/ubuntu18/level-3.dockerfile, docker/ubuntu18/level-4.dockerfile, docker/ubuntu18/level-5.dockerfile, docker/ubuntu20/level-2.dockerfile, docker/ubuntu20/level-3.dockerfile, docker/ubuntu20/level-4.dockerfile, docker/ubuntu20/level-5.dockerfile
=> Docker - Ubuntu Updates

docker/mivisionx-on-ubuntu18.dockerfile, docker/mivisionx-on-ubuntu20.dockerfile, docker/ubuntu18/level-5.dockerfile, docker/ubuntu20/level-5.dockerfile
=> Docker - RPP Update Version

README.md, amd_openvx_extensions/amd_winml/README.md
@kiritigowda The WinML apps need updates too, but I am still figuring that out. Will create a separate PR for those
=> Windows - README updates

amd_openvx/openvx/ago/ago_platform.h, amd_openvx_extensions/amd_opencv/README.md, amd_openvx_extensions/amd_winml/packages.config, amd_openvx_extensions/amd_winml/utilities/MIVisionX-WinML-Validate/MIVisionX-WinML-Validate.vcxproj, amd_openvx_extensions/amd_winml/vx_winml.vcxproj, apps/mivisionx_winml_classifier/README.md, apps/mivisionx_winml_yolov2/README.md
VS files needed updating to work with VS2019 
Fixes #674
=> WinML apps -  bug fixes

docker/centos8/level-4.dockerfile, docker/mivisionx-on-centos8.dockerfile, docker/mivisionx-on-ubuntu18.dockerfile, docker/mivisionx-on-ubuntu20.dockerfile, docker/ubuntu18/level-4.dockerfile, docker/ubuntu18/level-5.dockerfile, docker/ubuntu20/level-4.dockerfile, docker/ubuntu20/level-5.dockerfile
* MIOpen Updates
* CentOS 8 - Bug Fix
=> Docker - Updates & Bug Fixes

utilities/mv_deploy/mv_compile.cpp
Use python3 for model compiler
=> MV Compile - Update to Python3

.jenkins/common.groovy
* LCOV - Package Missing
* Python - Set explicit default
=> CI - CentOS 8 Updates

model_compiler/python/nnir_to_openvx.py
This PR adds support for finding the backend type (OCL or HIP) for the OpenVX, and it only links OpenCL libraries to the annmodule/anntest/annpython, only if the OpenVX's backend type is OCL.
@kiritigowda This PR has a dependency on [PR689](https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/pull/689), so it needs to be merged after PR689 gets merged.
=> NN model comiler - update the nnir_to_openvx script to detect the OpenVX backend

docker/conformance/openvx-1-3-on-centos7.dockerfile, docker/conformance/openvx-1-3-on-centos8.dockerfile, docker/conformance/openvx-1-3-on-ubuntu18.dockerfile, docker/conformance/openvx-1-3-on-ubuntu20.dockerfile, docker/conformance/system_info.py, docker/mivisionx-on-ubuntu18.dockerfile
CTS Dockers
* CentOS 7/8
* Ubuntu 18/20
=> Dockers - OpenVX 1.3 Conformance Dockers

model_compiler/python/nnir_to_clib.py
@LakshmiKumar23 could you please test this PR for the mv_objectdetect sample for the OpenCL backend only? Thanks.
=> NN mode compiler - update the nnir_to_clib script to create a tensor based on the detected OpenVX GPU backend

README.md
=> update README to add instructions for running the setup script for the HIP GPU backend

amd_openvx_extensions/amd_media/decoder.cpp
Changes required for using multiple hardware devices for video decoding in case of multi-stream decoding
=> amd_media - decoder multi-gpu support

tests/conformance_tests/README.md, tests/conformance_tests/runConformanceTests.py
* Run CTS on Linux
* Backend Support - ALL, HOST, OCL, & HIP
* Save CTS LOGs & System Info
=> Tests - Conformance Test Script

CHANGELOG.md, MIVisionX-setup.py, README.md
* Changelog added
* Setup updates
* Readme updates
=> MIVisionX - 2.0.0 Updates

docker/pytorch/mivisionx-with-pytorch.dockerfile
@kiritigowda ready to be merged. Made changes to reflect setup script and latest requirements
=> Update dockerfile for pytorch training

MIVisionX-setup.py, README.md, docker/mivisionx-on-ubuntu18.dockerfile, docker/mivisionx-on-ubuntu20.dockerfile, docker/pytorch/mivisionx-with-pytorch.dockerfile, docker/ubuntu18/level-5.dockerfile, docker/ubuntu20/level-5.dockerfile
* RPP Release Updates
+ Readme
+ Setup
+ Docker
=> MIVisionX Updates - RPP Release Updates

CHANGELOG.md, README.md
=> MIVisionX 2.0.0 - Release updates

CHANGELOG.md
=> Changelog - Updates

apps/cloud_inference/server_app/CMakeLists.txt
=> Apps - Inference Server App Fix

CHANGELOG.md
=> Changelog Updates

apps/bubble_pop/CMakeLists.txt, apps/bubble_pop/include/internal_opencvTunnel.h, apps/bubble_pop/include/internal_publishKernels.h, apps/bubble_pop/include/vx_ext_pop.h, apps/bubble_pop/include/vx_pop.h, apps/bubble_pop/source/AMD_VX_Pop_Bubble.cpp, apps/bubble_pop/source/AMD_VX_Pop_Donut.cpp, apps/bubble_pop/source/AMD_app.cpp, apps/bubble_pop/source/internal_dataTranslator.cpp, apps/bubble_pop/source/internal_publishKernels.cpp, apps/bubble_pop/source/internal_vxNodes.cpp
=> VX_Pop - Updates

samples/c_samples/canny/canny.cpp
=> fixes threshold API call

CHANGELOG.md, amd_openvx/openvx/ago/ago_interface.cpp, amd_openvx_extensions/amd_media/README.md, amd_openvx_extensions/amd_media/decoder.cpp, amd_openvx_extensions/amd_media/encoder.cpp, amd_openvx_extensions/amd_media/include/vx_amd_media.h, apps/bubble_pop/CMakeLists.txt, apps/bubble_pop/include/internal_opencvTunnel.h, apps/bubble_pop/include/internal_publishKernels.h, apps/bubble_pop/include/vx_ext_pop.h, apps/bubble_pop/include/vx_pop.h, apps/bubble_pop/source/AMD_VX_Pop_Bubble.cpp, apps/bubble_pop/source/AMD_VX_Pop_Donut.cpp, apps/bubble_pop/source/AMD_app.cpp, apps/bubble_pop/source/internal_dataTranslator.cpp, apps/bubble_pop/source/internal_publishKernels.cpp, apps/bubble_pop/source/internal_vxNodes.cpp, apps/cloud_inference/server_app/CMakeLists.txt, samples/c_samples/canny/canny.cpp
=> Develop: Merge to Master (#754)

tests/README.md
=> Tests - Readme Updates

utilities/rali/rocal_unittests/CMakeLists.txt, utilities/rali/rocal_unittests/README.md, utilities/rali/rocal_unittests/rocal_unittests.cpp
Changed name of rali_unittest to rocal_unittest.
=> rocAL - renamed rali_unittest to rocal_unittest

docker/mivisionx-on-centos7.dockerfile, docker/mivisionx-on-centos8.dockerfile, docker/mivisionx-on-ubuntu18.dockerfile, docker/mivisionx-on-ubuntu20.dockerfile, docker/pytorch/mivisionx-with-pytorch.dockerfile
@kiritigowda Rajy suggested we make our dockerfiles to install HIP by default
=> Docker - update to install HIP by default

amd_openvx_extensions/amd_media/README.md
Fix error in readme for the encoder
=> amd_media  - readme fix

amd_openvx/openvx/ago/ago_interface.cpp, amd_openvx/openvx/ago/ago_util_hip.cpp, amd_openvx_extensions/amd_media/decoder.cpp
The error message is modified to reflect EOS for amd_media
=> fix error message for EOS in amd_media encoder

CHANGELOG.md, MIVisionX-setup.py, README.md
=> RPP - Version upgrade

CHANGELOG.md, MIVisionX-setup.py, README.md
* MIVisionX 2.1.0 Release Updates
* RPP - V0.93
=> Develop - MIVisionX 2.1.0 Release  (#793)

model_compiler/python/nnir_to_openvx.py
* Model Compiler - OpenCV 4 Support (#796)
=> Develop - Merge to TOT (#796)

docker/conformance/openvx-1-3-on-ubuntu18.dockerfile, docker/conformance/openvx-1-3-on-ubuntu20.dockerfile, docker/mivisionx-on-ubuntu18.dockerfile, docker/mivisionx-on-ubuntu20.dockerfile, docker/mivisionx-opencl-on-ubuntu18.dockerfile, docker/mivisionx-opencl-on-ubuntu20.dockerfile, docker/pytorch/mivisionx-with-pytorch.dockerfile, docker/ubuntu18/level-5.dockerfile, docker/ubuntu20/level-5.dockerfile
=> Docker - HIP Backend Fix

CHANGELOG.md, MIVisionX-setup.py, README.md, docker/centos7/level-4.dockerfile, docker/centos8/level-4.dockerfile, docker/mivisionx-on-centos7.dockerfile, docker/mivisionx-on-centos8.dockerfile, docker/mivisionx-on-ubuntu18.dockerfile, docker/mivisionx-on-ubuntu20.dockerfile, docker/mivisionx-opencl-on-ubuntu18.dockerfile, docker/mivisionx-opencl-on-ubuntu20.dockerfile, docker/ubuntu18/level-4.dockerfile, docker/ubuntu18/level-5.dockerfile, docker/ubuntu20/level-4.dockerfile, docker/ubuntu20/level-5.dockerfile
Updates to ROCm CMake
* Setup
* Readme
* Dockers
@asalmanp @paveltc - to isolate the CMakeList warnings from @arvindcheru PR -- #786
=> ROCm CMake - Version Update to 5.1.0

MIVisionX-setup.py, README.md, docker/mivisionx-on-ubuntu18.dockerfile, docker/mivisionx-on-ubuntu20.dockerfile, docker/mivisionx-opencl-on-ubuntu18.dockerfile, docker/mivisionx-opencl-on-ubuntu20.dockerfile
* Setup Update
* Readme Update
* Docker - Ubuntu Updates
=> ROCm CMake - Use Master Branch

rocAL/rocAL/include/master_graph.h, rocAL/rocAL/source/rali_api_meta_data.cpp
trying to fix build error on OPENCL backend
=> fix build error for rocal opencl backend

docker/mivisionx-on-ubuntu18.dockerfile, docker/mivisionx-on-ubuntu20.dockerfile, docker/mivisionx-opencl-on-ubuntu18.dockerfile, docker/mivisionx-opencl-on-ubuntu20.dockerfile, docker/ubuntu18/level-2.dockerfile, docker/ubuntu18/level-3.dockerfile, docker/ubuntu18/level-4.dockerfile, docker/ubuntu18/level-5.dockerfile, docker/ubuntu20/level-2.dockerfile, docker/ubuntu20/level-3.dockerfile, docker/ubuntu20/level-4.dockerfile, docker/ubuntu20/level-5.dockerfile
* Ubuntu 20.04 - ROCm 5.1.1
* Ubuntu 18.04 - Fix & ROCm 5.1.1
=> Docker - ROCm Updates

amd_openvx_extensions/amd_nn/CMakeLists.txt, samples/c_samples/README.md, samples/gdf/README.md, samples/loom_360_stitch/README.md, samples/model_compiler_samples/README.md
* Add readme to install folder
=> Samples - Readme updates

CHANGELOG.md, MIVisionX-setup.py, README.md, docker/centos7/level-3.dockerfile, docker/centos7/level-4.dockerfile, docker/mivisionx-on-centos7.dockerfile, docker/mivisionx-on-ubuntu18.dockerfile, docker/mivisionx-on-ubuntu20.dockerfile, docker/mivisionx-opencl-on-ubuntu18.dockerfile, docker/mivisionx-opencl-on-ubuntu20.dockerfile, docker/ubuntu18/level-3.dockerfile, docker/ubuntu18/level-4.dockerfile, docker/ubuntu18/level-5.dockerfile, docker/ubuntu20/level-3.dockerfile, docker/ubuntu20/level-4.dockerfile, docker/ubuntu20/level-5.dockerfile
=> FFMPEG updates

apps/dg_test/CMakeLists.txt, apps/dg_test/DGtest.cpp, apps/dg_test/UserInterface.cpp
Added a support for Opencv 4.x on DGTest app since it wasn't included in issue #852
=> DGTest OpenCV 4.x support

CMakeLists.txt, apps/cloud_inference/server_app/inference.h, apps/cloud_inference/server_app/inference_hip.cpp
-Fixes the CMake Issue
-Using pinned memory pair for outputQ
=> Inference Server App Fix

MIVisionX-setup.py, README.md
=> Setup - Backend CPU Support

amd_openvx/openvx/ago/ago_util_opencl.cpp, docker/zenDNN/zenDNN-HIP.dockerfile, docker/zenDNN/zenDNN-cpu-only.dockerfile
=> ZenDNN - Docker Files

CHANGELOG.md, MIVisionX-setup.py, README.md, amd_openvx/cmake/FindOpenCL.cmake, apps/cloud_inference/server_app/cmake/FindOpenCL.cmake, docker/conformance/openvx-1-3-on-ubuntu18.dockerfile, docker/conformance/openvx-1-3-on-ubuntu20.dockerfile, docker/mivisionx-on-ubuntu18.dockerfile, docker/mivisionx-on-ubuntu20.dockerfile, docker/mivisionx-opencl-on-ubuntu18.dockerfile, docker/mivisionx-opencl-on-ubuntu20.dockerfile, docker/ubuntu18/level-2.dockerfile, docker/ubuntu18/level-3.dockerfile, docker/ubuntu18/level-4.dockerfile, docker/ubuntu18/level-5.dockerfile, docker/ubuntu20/level-2.dockerfile, docker/ubuntu20/level-3.dockerfile, docker/ubuntu20/level-4.dockerfile, docker/ubuntu20/level-5.dockerfile, docker/zenDNN/zenDNN-HIP.dockerfile, model_compiler/python/nnir_to_openvx.py, tests/library_tests/runLibraryTests.py, tests/vision_tests/runVisionTests.py
* ROCm - Updates
* Docker - Install ROCm & Graphics
* OpenCL - ROCm Dir Updates
* Setup - Half Install Updates
* Test - Remove OpenCL Failure for GFX 1030
* WarpPerspective_U8_U8_*
* Remap_S16_*
=> ROCm 5.2 - Updates (#893)

docker/mivisionx-on-ubuntu18.dockerfile, docker/mivisionx-on-ubuntu20.dockerfile, docker/mivisionx-opencl-on-ubuntu18.dockerfile, docker/mivisionx-opencl-on-ubuntu20.dockerfile, docker/pytorch/mivisionx-with-pytorch.dockerfile, docker/ubuntu18/level-4.dockerfile, docker/ubuntu18/level-5.dockerfile, docker/ubuntu20/level-4.dockerfile, docker/ubuntu20/level-5.dockerfile, docker/zenDNN/zenDNN-HIP.dockerfile
Docker 
* Half install updates
* PyTorch docker updates
=> Docker - Updates to half & Pytorch install

CHANGELOG.md, MIVisionX-setup.py, README.md, docker/mivisionx-on-ubuntu18.dockerfile, docker/mivisionx-on-ubuntu20.dockerfile, docker/mivisionx-opencl-on-ubuntu18.dockerfile, docker/mivisionx-opencl-on-ubuntu20.dockerfile, docker/pytorch/mivisionx-with-pytorch.dockerfile, docker/ubuntu18/level-5.dockerfile, docker/ubuntu20/level-5.dockerfile, docker/zenDNN/zenDNN-HIP.dockerfile
=> RPP - Version Update

amd_openvx/openvx/ago/ago_kernel_api.cpp, amd_openvx/openvx/hipvx/hip_host_decls.h, amd_openvx/openvx/hipvx/vision_kernels.cpp
Fix for Harris Corners giving a segfault with images size 1920x1080.
=> implemented fix for Harris Corners bug in HIP

amd_openvx/openvx/ago/ago_util_hip.cpp
background - HIP driver reports the number of WGPS by default for gfx10+ ASICS. each WGP represents two CUs. The GPU_ENABLE_WGP_MODE environment variable can also force the CU mode on gfx10+ ASICs.
=> OpenVX HIP backend - report correct number of CUs for gfx10+ in the logs

docker/README.md, docker/pytorch/README.md, docker/pytorch/mivisionx-with-pytorch.dockerfile
Allows user to pass the pytorch version argument to dockerfile under pytorch
=> add argument for specifying pytorch version for building docker file

docker/tensorflow/README.md, docker/tensorflow/mivisionx-with-tensorflow.dockerfile, rocAL/rocAL_pybind/example/new_api/tf_petsTrainingExample/README.md
@kiritigowda @asalmanp Fixed what I could. Commented on the other in #937
=> Codacy fixes for PR937

model_compiler/python/caffe_to_nnir.py, model_compiler/python/nnef_to_nnir.py, model_compiler/python/nnir_to_clib.py, model_compiler/python/nnir_to_nnef.py, model_compiler/python/nnir_to_openvx.py, model_compiler/python/nnir_update.py, model_compiler/python/onnx_to_nnir.py
- Model compiler codacy bugs. Fixes for all old scripts.
- Indentation fixes
@rrawther Fixes the * import error in all scripts as we discussed
=> model compiler script updates

tests/amd_migraphx_tests/runMIGraphXTests/runMIGraphXTests.cpp
Fixes codacy issue: https://app.codacy.com/gh/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/pullRequest?prid=10094614
=> code clean up

CHANGELOG.md, MIVisionX-setup.py, README.md
=> V2.3 - Updates

rocAL/rocAL_pybind/amd/rocal/pipeline.py
=> rocal: cleanup 

rocAL/rocAL_pybind/run.sh
Changing Python Lib Path for pybind installation
=> rocAL - Changing Python Lib Path

rocAL/rocAL_pybind/example/new_api/parse_config.py, rocAL/rocAL_pybind/example/new_api/rocAL_api_caffe_reader.py, rocAL/rocAL_pybind/run.sh
This fixes the issue with copyright violation from palameda scan
=> rocAL - fix for copy-write violation

amd_openvx_extensions/amd_media/decoder.cpp
This change adds the timing measurement parameters to the CLoomIoMediaDecoder class in order to measure the timing when running the decoder in a loop for multiple frames.
=> AMD Media Decoder - Added timing measurement to decoder looping option

CHANGELOG.md, CMakeLists.txt, MIVisionX-setup.py, README.md
Setup - RPP Version Updated to 0.98
=> RPP - Update version

rocAL/rocAL_pybind/run.sh
Uninstall the wheel , then install it making sure changes made to the wheel is reflected.
To resolve the issue - [https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/issues/980](https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/issues/980)
=> rocAL - Changes in run.sh file to uninstall & then install the Wheel

amd_openvx/openvx/ago/ago_drama_alloc.cpp, amd_openvx/openvx/ago/ago_util_hip.cpp, amd_openvx/openvx/api/vx_api.cpp
Create a separate stream for graph for kernel launch
=> OpenVX Graph hip stream fix

docker/pytorch/mivisionx-with-pytorch-with-mesa.dockerfile
Dockerfile for pytorch docker with mivisionx and mesa driver. 
This is a rocm5.3 ubuntu20.04 docker
=> docker - Pytorch with mesa driver

docker/pytorch/mivisionx-with-pytorch-with-mesa.dockerfile
=> Docker - PyTorch Fix

CHANGELOG.md, MIVisionX-setup.py, README.md, docker/archive/mivisionx-opencl-on-ubuntu20.dockerfile, docker/mivisionx-on-ubuntu20.dockerfile, docker/mivisionx-on-ubuntu22.dockerfile, docker/pytorch/mivisionx-with-pytorch-with-mesa.dockerfile, docker/pytorch/mivisionx-with-pytorch.dockerfile, docker/tensorflow/mivisionx-with-tensorflow.dockerfile, docker/ubuntu20/level-5.dockerfile, docker/ubuntu22/level-5.dockerfile
=> RPP - Upgrade to V0.99

CHANGELOG.md, CMakeLists.txt, MIVisionX-setup.py, README.md, amd_openvx/cmake/FindAMDRPP.cmake, amd_openvx_extensions/amd_custom/custom_lib/CMakeLists.txt, apps/cloud_inference/server_app/CMakeLists.txt, apps/dg_test/CMakeLists.txt, apps/image_augmentation/CMakeLists.txt, apps/mivisionx_openvx_classifier/CMakeLists.txt, docker/archive/mivisionx-opencl-on-ubuntu20.dockerfile, docker/mivisionx-on-ubuntu20.dockerfile, docker/mivisionx-on-ubuntu22.dockerfile, docker/pytorch/mivisionx-with-pytorch-with-mesa.dockerfile, docker/pytorch/mivisionx-with-pytorch.dockerfile, docker/tensorflow/mivisionx-with-tensorflow.dockerfile, docker/ubuntu20/level-5.dockerfile, docker/ubuntu22/level-5.dockerfile, model_compiler/python/nnir_to_clib.py
* RPP Version Update
* RPATH set
* Setup Support for RedHat 9 and bug fixes
=> ROCm V5.5.0 - Updates

MIVisionX-setup.py, README.md
Setup
* Install Dev options
* Fix reinstall for NN deps
* SLES Fix
=> Setup - Install Dev Options

CMakeLists.txt, docker/linux/mivisionx-on-rhel-8.dockerfile, docker/linux/mivisionx-on-rhel-9.dockerfile, docker/linux/mivisionx-on-sles-15.dockerfile, tests/library_tests/runLibraryTests.py, tests/neural_network_tests/runNeuralNetworkTests.py, tests/vision_tests/runVisionTests.py
* Dockers
+ RHEL-8
+ RHEL-9
+ SLES 15 SP3
=> Linux - Distro Docker Support

CMakeLists.txt
@arvindcheru - for SWDEV-375660 to be tested with ROCm 5.5
=> CMakeLists - Avoid RPATH removal from binaries (#1041)

amd_openvx_extensions/amd_nn/src/convolution_layer.cpp, amd_openvx_extensions/amd_nn/src/deconvolution_layer.cpp
Deconvolution and convolution bug fix for [issue on MIOpen](https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1982)
=> AMD_NN - bug fix

toolkit/amd_data_analysis_toolkit/classification/generate-visualization.py
=> ADAT - Fix for Deprecated Function

rocAL/rocAL_pybind/examples/prefetch_queue_depth/README.md, rocAL/rocAL_pybind/examples/prefetch_queue_depth/prefetch_queue_depth.py
- Reintroduce the python example
- Update the python script to use latest rocal python API
- Update README
=> rocAL - Prefetch queue depth python example

tests/library_tests/runLibraryTests.py
Check libraries built in CPU backend - Updates
NN OCL backends not supported in newer rocm
=> Library Test - Updates to CPU Backend

CHANGELOG.md, MIVisionX-setup.py, README.md, amd_openvx/cmake/FindAMDRPP.cmake, amd_openvx_extensions/CMakeLists.txt, docker/archive/mivisionx-opencl-on-ubuntu20.dockerfile, docker/linux/mivisionx-on-rhel-8.dockerfile, docker/linux/mivisionx-on-rhel-9.dockerfile, docker/linux/mivisionx-on-sles-15.dockerfile, docker/mivisionx-on-ubuntu20.dockerfile, docker/mivisionx-on-ubuntu22.dockerfile, docker/pytorch/mivisionx-with-pytorch-with-mesa.dockerfile, docker/pytorch/mivisionx-with-pytorch.dockerfile, docker/tensorflow/mivisionx-with-tensorflow.dockerfile, docker/ubuntu20/level-5.dockerfile, docker/ubuntu22/level-5.dockerfile, rocAL/rocAL/CMakeLists.txt, rocAL/rocAL_pybind/CMakeLists.txt
* RPP Version - Update to 1.0.0 (#1058)
* Changelog Updates
=> Develop - Merge 2.4.0 Updates

model_compiler/python/nnir_to_openvx.py, model_compiler/python/onnx_to_nnir.py
-updated the onnx_to_nnir python script to handle different tensor data values which fixes the empty raw data files
=> Model Compiler - ONNX update

amd_openvx_extensions/amd_nn/src/activation_layer.cpp, amd_openvx_extensions/amd_nn/src/batch_normalization_layer.cpp, amd_openvx_extensions/amd_nn/src/convolution_layer.cpp, amd_openvx_extensions/amd_nn/src/deconvolution_layer.cpp, amd_openvx_extensions/amd_nn/src/fully_connected_layer.cpp, amd_openvx_extensions/amd_nn/src/kernels.cpp, amd_openvx_extensions/amd_nn/src/kernels.h, amd_openvx_extensions/amd_nn/src/local_response_normalization_layer.cpp, amd_openvx_extensions/amd_nn/src/normalization_layer.cpp, amd_openvx_extensions/amd_nn/src/pooling_layer.cpp, amd_openvx_extensions/amd_nn/src/reshape_layer.cpp, amd_openvx_extensions/amd_nn/src/scale_layer.cpp, amd_openvx_extensions/amd_nn/src/softmax_layer.cpp, amd_openvx_extensions/amd_nn/src/tensor_add.cpp, amd_openvx_extensions/amd_nn/src/tensor_matrix_multiply.cpp, amd_openvx_extensions/amd_nn/src/tensor_max.cpp, amd_openvx_extensions/amd_nn/src/tensor_min.cpp, amd_openvx_extensions/amd_nn/src/tensor_multiply.cpp, amd_openvx_extensions/amd_nn/src/tensor_subtract.cpp
Reverting all the renaming of graphHandle to RPPHandle for amd_nn source files
=> rocAL/NN - Reverting renaming of graphHandle to RPPHandle

rocAL/rocAL/include/decoders/image/hw_jpeg_decoder.h, rocAL/rocAL/source/decoders/image/hw_jpeg_decoder.cpp
Fixes the bug which was causing crash in MI300 when using hwdec
=> hwdec fix bug which was causing crash in MI300

docs/.sphinx/requirements.txt
=> Develop - Merge to master

CMakeLists.txt, tests/openvx/CMakeLists.txt, tests/openvx/canny/CMakeLists.txt, tests/openvx/canny/canny.cpp, tests/openvx/channel_extract/CMakeLists.txt, tests/openvx/channel_extract/channel_extract.cpp, tests/openvx/color_convert/CMakeLists.txt, tests/openvx/color_convert/color_convert.cpp
=> CTest - Add Basic Tests

model_compiler/python/nnef_to_nnir.py, model_compiler/python/nnir_to_clib.py, utilities/mv_deploy/CMakeLists.txt, utilities/mv_deploy/README.md, utilities/mv_deploy/mv_compile.cpp
-added a support for nnef & onnx models
-fixed a bug in nnir_to_clib.py to handle multiple outputs
=> mv_compile - update

model_compiler/python/nnir_to_clib.py, tests/vision_tests/runVisionTests.py
* Fix CentOS 7 Build package issue
* Fix Vision Test
=> CentOS 7 - Fix

model_compiler/python/nnir_to_clib.py, utilities/mv_deploy/CMakeLists.txt
Fixed an indentation error
Added filesystem library linkage to CMakeLists.txt
=> NNIR_CLIB - Fix

rocAL/README.md
=> rocAL - Readme Updates

docker/mivisionx-on-ubuntu20.dockerfile, docker/mivisionx-on-ubuntu22.dockerfile, docker/pytorch/mivisionx-with-pytorch-with-mesa.dockerfile, docker/pytorch/mivisionx-with-pytorch.dockerfile, docker/tensorflow/mivisionx-with-tensorflow.dockerfile, docker/ubuntu20/level-5.dockerfile, docker/ubuntu22/level-5.dockerfile
=> Docker - rocAL Updates

CHANGELOG.md, MIVisionX-setup.py, README.md, docker/archive/mivisionx-opencl-on-ubuntu20.dockerfile, docker/linux/mivisionx-on-rhel-8.dockerfile, docker/linux/mivisionx-on-rhel-9.dockerfile, docker/linux/mivisionx-on-sles-15.dockerfile, docker/mivisionx-on-ubuntu20.dockerfile, docker/mivisionx-on-ubuntu22.dockerfile, docker/pytorch/mivisionx-with-pytorch-with-mesa.dockerfile, docker/pytorch/mivisionx-with-pytorch.dockerfile, docker/tensorflow/mivisionx-with-tensorflow.dockerfile, docker/ubuntu20/level-5.dockerfile, docker/ubuntu22/level-5.dockerfile
* RPP - Updated to Version 1.2.0 
* Changelog - Updates
=> Version 2.5.0 - Updates

CHANGELOG.md, MIVisionX-setup.py, README.md, utilities/mv_deploy/mv_compile.cpp
* Setup - Update SLES install for RPP
* Readme & Changelog updates
=> SLES - Updates

amd_openvx_extensions/amd_rpp/source/kernel_rpp.cpp
=> VX_RPP - Fix

.Doxyfile
Oxygen File renamed to Doxyfile
=> Fix Doxygen File

amd_openvx/openvx/include/vx_ext_amd.h, amd_openvx_extensions/amd_custom/include/vx_amd_custom.h, amd_openvx_extensions/amd_media/include/vx_amd_media.h, amd_openvx_extensions/amd_migraphx/include/vx_amd_migraphx.h, amd_openvx_extensions/amd_nn/include/vx_amd_nn.h, amd_openvx_extensions/amd_opencv/include/internal_publishKernels.h, amd_openvx_extensions/amd_opencv/include/vx_ext_opencv.h, amd_openvx_extensions/amd_opencv/source/internal_publishKernels.cpp, amd_openvx_extensions/amd_opencv/source/internal_vxNodes.cpp, amd_openvx_extensions/amd_rpp/include/internal_publishKernels.h, amd_openvx_extensions/amd_rpp/include/vx_ext_rpp.h, amd_openvx_extensions/amd_winml/include/vx_ext_winml.h
* Cleanup
* Fix Doxygen comments
=> vx_ext_amd - updates & cleanup

CMakeLists.txt
MIVisionX asan package name was not having 'asan' suffix. Added the same
=> SWDEV-416815 - Added suffix 'asan' to ASAN package name

rocAL/CMakeLists.txt, rocAL/rocAL/CMakeLists.txt, rocAL/rocAL/include/loaders/image/loader_module.h, rocAL/rocAL/include/meta_data/caffe2_meta_data_reader.h, rocAL/rocAL/include/meta_data/caffe2_meta_data_reader_detection.h, rocAL/rocAL/include/meta_data/caffe_meta_data_reader.h, rocAL/rocAL/include/meta_data/caffe_meta_data_reader_detection.h, rocAL/rocAL/include/meta_data/mxnet_meta_data_reader.h, rocAL/rocAL/include/meta_data/randombboxcrop_meta_data_reader.h, rocAL/rocAL/include/readers/image/caffe2_lmdb_record_reader.h, rocAL/rocAL/include/readers/image/caffe_lmdb_record_reader.h, rocAL/rocAL/include/readers/image/cifar10_data_reader.h, rocAL/rocAL/include/readers/image/coco_file_source_reader.h, rocAL/rocAL/include/readers/image/file_source_reader.h, rocAL/rocAL/include/readers/image/image_reader.h, rocAL/rocAL/include/readers/image/mxnet_recordio_reader.h, rocAL/rocAL/include/readers/image/reader_factory.h, rocAL/rocAL/include/readers/image/tf_record_reader.h, rocAL/rocAL/include/readers/video/sequence_file_source_reader.h, rocAL/rocAL/source/meta_data/caffe2_meta_data_reader.cpp, rocAL/rocAL/source/meta_data/caffe2_meta_data_reader_detection.cpp, rocAL/rocAL/source/meta_data/caffe_meta_data_reader_detection.cpp, rocAL/rocAL/source/readers/image/caffe2_lmdb_record_reader.cpp, rocAL/rocAL_pybind/CMakeLists.txt
This fix is required for 5.7 release branch.
=> rocAL - Compile failure fix

MIVisionX-setup.py, model_compiler/python/nnir_to_clib.py, model_compiler/python/nnir_to_openvx.py, tests/neural_network_tests/runNeuralNetworkTests.py
* include dirs updated
* rocm path added
* Fix bugs
=> Model Compiler - Update & Bug Fixes

CHANGELOG.md, MIVisionX-setup.py, README.md, docker/mivisionx-on-ubuntu20.dockerfile, docker/mivisionx-on-ubuntu22.dockerfile, docker/pytorch/mivisionx-with-pytorch-with-mesa.dockerfile, docker/pytorch/mivisionx-with-pytorch.dockerfile, docker/tensorflow/mivisionx-with-tensorflow.dockerfile, docker/ubuntu20/level-5.dockerfile, docker/ubuntu22/level-5.dockerfile
Fix for Python 3.8.X CuPy Support.
Use CuPy v12.2.0 instead of master
=> CuPy - Version Updates

amd_openvx_extensions/amd_nn/src/reshape_layer.cpp
=> VX_NN Reshape Layer Bug Fix

CHANGELOG.md, CMakeLists.txt, MIVisionX-setup.py, README.md, amd_openvx/cmake/FindHALF.cmake, amd_openvx/openvx/include/vx_ext_amd.h, amd_openvx_extensions/amd_nn/src/reshape_layer.cpp
* half.hpp directories added
* half required to be turned on by default for fp16 inference
=> Half - Find & Add Directories

amd_openvx/cmake/FindHALF.cmake, amd_openvx_extensions/amd_nn/src/reshape_layer.cpp, amd_openvx_extensions/amd_rpp/source/tensor/Copy.cpp
* Find Half - Add ROCM ENV Variable find
* Use vx_float16 only if half found
=> Half - Support Updates

amd_openvx/cmake/FindHALF.cmake, amd_openvx_extensions/amd_nn/src/reshape_layer.cpp, amd_openvx_extensions/amd_rpp/source/tensor/Copy.cpp, apps/image_augmentation/CMakeLists.txt, docs/.sphinx/requirements.txt, utilities/rocAL/rocAL_basic_test/CMakeLists.txt, utilities/rocAL/rocAL_dataloader/CMakeLists.txt, utilities/rocAL/rocAL_dataloader_tf/CMakeLists.txt, utilities/rocAL/rocAL_performance_tests/CMakeLists.txt, utilities/rocAL/rocAL_performance_tests_with_depth/CMakeLists.txt, utilities/rocAL/rocAL_unittests/CMakeLists.txt, utilities/rocAL/rocAL_video_unittests/CMakeLists.txt
=> Develop - Merge to TOT

amd_openvx_extensions/amd_rpp/source/tensor/Vignette.cpp
Added fix for OPENCL backend wrt recent VX_RPP changes
Issue #1210
=> VX_RPP Fix build with OPENCL backend

rocAL/rocAL_pybind/CMakeLists.txt, rocAL/rocAL_pybind/setup.py
Fix for #1208 - Use Half Include DIrs
=> PyBind11 - Add Half Path

CMakeLists.txt
* Setup & Install package diff fix
=> Package - Fix Setup/Install Diff

CHANGELOG.md, CMakeLists.txt, MIVisionX-setup.py, README.md, docker/archive/mivisionx-opencl-on-ubuntu20.dockerfile, docker/linux/mivisionx-on-rhel-8.dockerfile, docker/linux/mivisionx-on-rhel-9.dockerfile, docker/linux/mivisionx-on-sles-15.dockerfile, docker/mivisionx-on-ubuntu20.dockerfile, docker/mivisionx-on-ubuntu22.dockerfile, docker/pytorch/mivisionx-with-pytorch-with-mesa.dockerfile, docker/pytorch/mivisionx-with-pytorch.dockerfile, docker/tensorflow/mivisionx-with-tensorflow.dockerfile, docker/ubuntu20/level-5.dockerfile, docker/ubuntu22/level-5.dockerfile
=> CMakeList - ROCm Path Options

MIVisionX-setup.py, README.md
=> Setup - CuPy Updates

.github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/issue_report.yml
Hello, this PR is introducing a new issue template for ROCm public repositories to make it easier for users to submit the details for issues and bugs. Problems pertaining to documentation or non-bug related, users have the ability to open a blank issue template to submit their report. 
Thank you,
Community Support Team (ML SW SDK)
=> Adding issue template

CMakeLists.txt, tests/CMakeLists.txt, tests/ctest_cmakelists/CMakeLists.txt
* make test - updates
* CTest support for test package
=> Test package - updates

.github/CODEOWNERS, CHANGELOG.md, CMakeLists.txt, MIVisionX-setup.py, README.md, docs/sphinx/requirements.in, docs/sphinx/requirements.txt
* Documentation updates
* RPP upgrades
=> Develop - Merge into master

apps/mivisionx_winml_yolov2/README.md, tests/amd_migraphx_tests/gdf/README.md, tests/amd_migraphx_tests/mnist/README.md, tests/amd_migraphx_tests/resnet50/README.md
Some onnx model links were outdated, hence updated.
=> ONNX Link Updates

model_compiler/python/nnir_to_openvx.py, model_compiler/python/nnir_to_zendnn.py, model_compiler/python/onnx_to_nnir.py, rocAL/docs/examples/image_processing/inference_pipeline.py, rocAL/rocAL_pybind/amd/rocal/fn.py, tests/library_tests/runLibraryTests.py, tests/neural_network_tests/runNeuralNetworkTests.py, tests/smoke_tests/Inference/inference-measure-accuracy.py
Removes : unsed imports , trailing semicolons and refactors "not X in" to "X not in" for pep-8 conformance
=> Cleanup and fixes for pep-8 conformance - II

.github/CODEOWNERS
Update CODEOWNERS syntax, missed asterisk
=> Update CODEOWNERS syntax, missed asterisk

rocAL/rocAL_pybind/README.md, rocAL/rocAL_pybind/examples/README.md
Some Markdown changes to follow Markdown linting rules
=> docs: Change Markdown formatting for READMEs for ReadtheDocs

cmake/FindMIVisionX.cmake
Remove unnecessary variable : MIVisionX_LIBRARIES_DIRS
=> CMakeLists.txt update to remove unnecessary variable

MIVisionX-setup.py, model_compiler/README.md, tests/neural_network_tests/runNeuralNetworkTests.py
Cherry-fix for NN Test failure
=> NN Test - Fix for ONNX failure

.Doxyfile, docs/doxygen/Doxyfile
* Docs - Update Doxyfile (#1301)
* Update .Doxyfile
---------
=> Docs - Update Doxyfile (#1301) (#1302)

README.md, amd_openvx_extensions/amd_migraphx/README.md, amd_openvx_extensions/amd_winml/samples/README.md, apps/README.md, apps/dg_test/README.md, apps/mivisionx_winml_classifier/README.md, docs/.sphinx/_toc.yml.in, docs/doxygen/Doxyfile, samples/loom_360_stitch/README.md, utilities/runvx/README.md
Updated top-level README
Updated doxyfile to remove README
updated _toc.yml.in for root:README
updated misc files to correct URLs and images
=> Fix broken links for 6.0.2

docs/sphinx/_toc.yml.in
edited _toc.yml.in to restore API reference content
=> update TOC for API Ref

cmake/FindHALF.cmake
* Find Half with variable
* Use ROCm Half
=> Find Half - Fix

.gitignore, docs/index.rst, docs/install/amd_openvx-install.rst, docs/install/model-compiler-install.rst, docs/sphinx/_toc.yml.in
minor edits for consistency in TOC and Index, and other files
=> Leo's edits

amd_openvx_extensions/amd_rpp/include/internal_rpp.h, amd_openvx_extensions/amd_rpp/source/kernel_rpp.cpp, amd_openvx_extensions/amd_rpp/source/tensor/Spectrogram.cpp
- Fix build issues with Spectrogram
- Introduce layouts as NHW, NFT, NTF for audio cases
- Modify Spectrogram to pass layouts
=> Introduce Audio Layout and fix Spectrogram 

.azuredevops/rocm-ci.yml
For build triggers in public-facing CI project on Azure Pipelines: https://dev.azure.com/ROCm-CI/ROCm-CI/_build
=> Enable external CI pipeline triggers

amd_openvx_extensions/amd_rpp/source/tensor/Resample.cpp
- Fix Resample compile errors with older versions of RPP
=> Fix Resample compile errors

MIVisionX-setup.py, docker/mivisionx-on-ubuntu20.dockerfile, docker/ubuntu20/level-5.dockerfile, docker/ubuntu22/level-5.dockerfile, docs/install/model-compiler-install.rst, model_compiler/README.md, tests/neural_network_tests/runNeuralNetworkTests.py
TOT NNEF has restructured the folders. Now using a branch I created.
=> NNEF - Use V1.0.0 Branch

MIVisionX-setup.py, tests/neural_network_tests/runNeuralNetworkTests.py
RHEL 8.X requires numpy version 1.19.5
=> RHEL 8 - Fix PIP package

amd_openvx_extensions/amd_rpp/include/vx_ext_rpp_version.h
Merge after #1326 
Patch version update to signify audio support
=> VX_RPP - update patch for audio support

docs/install/installation.rst
* Update installation.rst
fix broken link
* Update installation.rst
added a period, and used Leo's suggested text
---------
=> Update installation.rst (#1373)

CHANGELOG.md, MIVisionX-setup.py, README.md
* Setup Updates
```
MIVisionX Dependencies Re-Installed with MIVisionX-setup.py V-3.4.0 on Linux-6.5.0-35-generic-x86_64-with-centos-7.9.2009-Core-redhat-7
```
=> Centos 7 - Support Updates 

CHANGELOG.md, MIVisionX-setup.py, README.md, tests/neural_network_tests/runNeuralNetworkTests.py
* Setup updates
* Test updates
=> Ubuntu 24.04 - Support Updates

amd_openvx_extensions/amd_rpp/source/tensor/ToDecibels.cpp
Add fix for toDecibels augmentation for updating the destination ROI.
=> Audio PR: Todecibels Fix for dst roi updation

CHANGELOG.md, MIVisionX-setup.py, README.md, tests/neural_network_tests/runNeuralNetworkTests.py
* Fix pip packages
* Fix OpenCV
=> Setup - SLES 15 SP5 Updates

MIVisionX-setup.py, tests/neural_network_tests/runNeuralNetworkTests.py
SLES 15 SP5 - Fix missing pip packages
=> SLES -  pip updates

amd_openvx_extensions/amd_rpp/source/tensor/Resample.cpp
Fixes the build issue with ToT rpp due to repeated definition of windowed_sinc function for Resample kernel
=> Fixing Resample build issue

amd_openvx_extensions/amd_rpp/source/tensor/Resample.cpp
=> Revert "Fixing Resample build issue"

CHANGELOG.md, CMakeLists.txt, MIVisionX-setup.py, README.md
Package - Disable rocdecode dependency
=> Package - Updates

docs/doxygen/Doxyfile
to fix path
eg
https://rocm.docs.amd.com/projects/MIVisionX/en/docs-6.0.2/doxygen/html/vx__api_8h.html
=> Strip Read the Docs dir from doxygen path

CMakeLists.txt
=> CMakeLists - Default GPU List Updates

docs/tutorials/mivisionx-tests.rst
(cherry picked from commit aa81294b4dacee14fd6491f7e594f85c08533a97)
=> fixed broken links and removed one link

CHANGELOG.md, CMakeLists.txt, README.md, docs/install/installation.rst, tests/CMakeLists.txt
* Readme - Updates
* Version updates for 7.1
=> Docs - Updates and fixes
