MIVisionX-setup.py
README.md

* sudo requirement removed
* fixed bugs

 MIVisionX Setup Script Fix

---

model_compiler/python/nnir.py

Fixed bug caused by using fp16 tensors with batch norm.

fixed so that batch norm layer does not convert tensors to FP16

---

.travis.yml

MIVisionX Official Docker used for build testing with Travis for PRs, commits, and regressions.

Travis - Use MIVisionX Docker

---

utilities/runvx/runvx.cpp

added feature for runvx to work from the cwd of the gdf rather than the cwd of where runvx is being called from.

relative path decode for runvx

---

model_compiler/python/caffe_pb2.py
model_compiler/python/caffe_to_nnir.py
model_compiler/python/nnir.py
model_compiler/python/nnir_to_openvx.py

1. Adding support in caffe_to_nnir for reshape, flatten, permute , prior box
2. Adding support for flatten, permute and prior box in nnir and nnir_to_openvx
3. Fixes bug in concat in caffe_to_nnir and niir

Support for permute, prior box and flatten in model_compiler

---

amd_openvx_extensions/amd_nn/src/permute_layer.cpp

VX_NN - Warning Fix

---

CMakeLists.txt
apps/CMakeLists.txt

- Default package installation dir is set to /opt/rocm
Signed-off-by: Pruthvi Madugundu <pruthvi.madugundu@amd.com>

MIVisionX - Changes to support relocatable ROCm installation

---

CMakeLists.txt

fix for getting MIVisionX not installed to default (/usr/local)

CMake - install prefix fix

---

MIVisionX-setup.py
README.md

* MIOpen Version upgrade - 2.5.0 to accommodate 3.6 ROCm changes.

Setup Update - MIOpen Default - 2.5.0

---

.travis.yml

Travis updates - remove ROCm install
* Hardware support on Travis for ROCm unknown. The docker has preinstalled all dependencies.
* No tests run to exercise the hardware

Travis CI Updates

---

MIVisionX-setup.py
README.md

#369 - Failure due to boost static lib missing fixed
```
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Radeon Performance Primitives (RPP) Version -- 0.5
-- RPP install path set to -- /opt/rocm/rpp
-- cmake minimum version required: 3.5
-- cmake …
```

Setup - Boost shared and static lib

---

utilities/loom_shell/loom_shell_util.cpp

* Loom Shell works fine on a single GPU system
* Loom Shell on the multi-GPU system was not enabled
* This fix supports multi-GPU but uses GPU[0] to run the workload

Loom Shell Multi-GPU support

---

MIVisionX-setup.py

ccmake command from 'make-Makefiles.bash' opens a cmake GUI and halts the installation.
replaced 'make-Makefiles.bash' with "cmake -G "Unix Makefiles" ../../source"

Updated x265 build instruction to skip cmake GUI

---

CMakeLists.txt

- Package names are formed as per the conventions.
- ROCm version is appended to the version field when built by CI.
- make target 'package' tries building deb, rpm, zip and tz.

Package update to support ROCm upgrade

---

amd_openvx/openvx/ago/ago_interface.cpp

set the graph state to VX_GRAPH_STATE_ABANDONED if the requested action is VX_ACTION_ABANDON

openVX HIP GPU backend - fix a bug for Graph.GraphState test

---

amd_openvx/openvx/ago/ago_haf_gpu_corners.cpp
amd_openvx/openvx/ago/ago_internal.h
amd_openvx/openvx/ago/ago_kernel_api.cpp
amd_openvx/openvx/ago/ago_util.cpp
amd_openvx/openvx/ago/ago_util_hip.cpp
amd_openvx/openvx/ago/ago_util_opencl.cpp

- this PR fixes the Graph.VirtualArray conformance test for HIP backend. This
test makes use of the num_corners (scalar output vlaue) of FastCorner node which
was missing support in HIP backend.

OpenVX HIP GPU backend - add support for scalar output sync

---

amd_openvx/openvx/hipvx/color_kernels.cpp

This PR fixes the color conversions for the following formats:
RGB->NV12, RGB->IYUV, UYVY->NV12, UYVY->IYUV, YUYV->NV12, YUYV->IYUV

OpenVX HIP GPU backend - fix a bug for ColorKernels

---

amd_openvx/openvx/ago/ago_kernel_api.cpp
amd_openvx/openvx/api/vx_api.cpp

Check input image instead of output for the threshold data type. This fixes all the vxCanny CTS failures.
Added a support for int16 data type for threshold since it is now supported in OpenVX 1.3. This fixes all the vxThreshold CTS failures that were introduced by the above fix.

CTS Bug Fix for vxCanny & Support for int16 Threshold data type

---

amd_openvx/openvx/ago/ago_kernel_api.cpp
amd_openvx/openvx/hipvx/hip_host_decls.h
amd_openvx/openvx/hipvx/vision_kernels.cpp

- use a generic pointer to point to the shared memory
- use individual comparison when calculating harris scores
- don't pre-add the offset to the array containing the detected corners, as the first few bytes reserved for the total identified number of corners
- use atomicAdd instead of atomicInc
- use builtin __float_as_uint for presenting float as uint

OpenVX HIP GPU backend - fix bugs for HarrisCorner3x3 kernels

---

amd_openvx_extensions/amd_rpp/source/BrightnessbatchPD.cpp
amd_openvx_extensions/amd_rpp/source/ResizebatchPD.cpp

Fixes bug where there is no output for certain test cases for OpenCL backend

amd_rpp - force gpu affinity to cpu for running without codegen

---

amd_openvx/openvx/api/vx_api.cpp

* CMake Log 
```
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- MIVisionX Version -- 2.0.0
-- MIVisionX Install Path -- /opt/rocm/mivisionx
-- MIVisionX Build Type -- Release
-- MIVisionX Backend set to OPENCL
-- MIVisionX Developer Options
-- …
```

GCC 9 - CPU Warning Fix

---

amd_openvx/openvx/ago/ago_kernel_api.cpp
amd_openvx/openvx/hipvx/filter_kernels.cpp
amd_openvx/openvx/hipvx/hip_host_decls.h

This PR addresses issue #541 for HIP GPU backend.

VisionTest HIP GPU backend - Fix a segfault for opticalFlowLK gdf test

---

rocAL/rocAL_pybind/CMakeLists.txt

Fixes link issue where library is not found.

rocal_pybind - fix for package link error

---

rocAL/rocAL_pybind/CMakeLists.txt

Fix rocAL Pybind 
* Top level CMakeLists not used in run.sh
* Link path set in top level CMake needs adding the run.sh to clean build pybind
This PR is a temp fix to allow existing tests to work

rocAL Pybind - Temp Fix

---

amd_openvx_extensions/amd_nn/src/cast_layer.cpp

Support for FLOAT32 output type (used in mobilenet-ssd) already exists. Had missed it in validate. Figured this while creating GDFs for testing.
@kiritigowda Ready to be merged
@paveltc change required for the GDF we tested yesterday

Cast Layer - adding validate support

---

docker/centos7/level-3.dockerfile
docker/centos7/level-4.dockerfile
docker/mivisionx-on-centos7.dockerfile

Docker - CentOS 7 Fix

---

amd_openvx_extensions/amd_nn/src/topk_layer.cpp

Issue seen by @asalmanp while running runvx for topK layer is fixed by this PR
```
free(): invalid next size (fast)
Aborted (core dumped)
```

Bug Fix - topK layer

---

docker/centos7/level-1.dockerfile
docker/centos7/level-2.dockerfile
docker/centos7/level-3.dockerfile
docker/centos7/level-4.dockerfile
docker/centos8/level-1.dockerfile
docker/centos8/level-2.dockerfile
docker/centos8/level-3.dockerfile
docker/centos8/level-4.dockerfile
docker/mivisionx-on-centos7.dockerfile
docker/mivisionx-on-centos8.dockerfile

* CentOS 7 - Updates
* CentOS 8 - Bugfix and Updates

Docker - CentOS 7/8 MIVisionX Support Updates

---

amd_openvx/openvx/ago/ago_kernel_api.cpp
amd_openvx/openvx/ago/ago_platform.cpp
amd_openvx/openvx/ago/ago_platform.h

* Set agoSetEnvironmentVariable("AGO_BUFFER_MERGE_FLAGS", "1") harrisCorners - Only if Target Set to GPU
* Need to Unset the Variable after HarrisCorners GPU is complete

Issue 558 -  vxMapRemapPatch.MapRandomRemap Random Failure Fix

---

amd_openvx/openvx/ago/ago_drama_alloc.cpp
amd_openvx/openvx/ago/ago_kernel_api.cpp
amd_openvx/openvx/api/vx_api.cpp

PR#596 introduced a regression for HarrisCorner and it is causing a segfault for this node. PR#596 added an extra if check to set AGO_BUFFER_MERGE_FLAGS if the device_type is GPU but the issue is that the device_type is not initialized when we reach the ovxKernel_HarrisCorners function. 
This PR removes this extra if and it makes sure that the AGO_BUFFER_MERGE_FLAGS is unset if HarrisCorner is used in the graph.

OpenVX GPU backend - fix a regression for HarrisCorner node introduced by PR#596

---

amd_openvx/openvx/ago/ago_internal.h
amd_openvx_extensions/amd_loomsl/live_stitch_api.cpp
amd_openvx_extensions/amd_nn/src/kernels.cpp

Issue #458 Fix
```
Scanning dependencies of target runcl
Scanning dependencies of target openvx
[  1%] Building CXX object utilities/runcl/CMakeFiles/runcl.dir/runcl.cpp.o
[  2%] Building CXX object amd_openvx/openvx/CMakeFiles/openvx.dir/ago/ago_drama_divide.cpp.o
[  3%] Building CXX object amd_openvx/openvx/CMakeFiles/openvx.dir/ago/ago_haf_cpu.cpp.o
[  5%] Building CXX object amd_openvx/openvx/CMakeFiles/openvx.dir/ago/ago_drama_merge.cpp.o
[  6%] Building CXX object amd_openvx/openvx/CMakeFiles/openvx.dir/ago/ago_drama_analyze.cpp.o
[  7%] Building CXX object amd_openvx/openvx/CMakeFiles/openvx.dir/ago/ago_drama.cpp.o
[  8%] Building CXX object amd_openvx/openvx/CMakeFiles/openvx.dir/ago/ago_drama_alloc.cpp.o
[ 10%] Building CXX object …
```

Issue #458 Fix - GNU 9.3.0: Warnings & Error Handling 

---

amd_openvx/openvx/ago/ago_kernel_api.cpp
amd_openvx/openvx/hipvx/geometric_kernels.cpp
amd_openvx/openvx/hipvx/hip_common_funcs.h
amd_openvx/openvx/hipvx/hip_host_decls.h

- This PR fixes the failures reported in issue #566 for the HIP backend for WarpPerspective kernels where out-of-bound access caused a segfault.

OpenVX HIP GPU backend - fix failures reported in issue #566 for HIP backend

---

README.md
amd_openvx/README.md
amd_openvx/openvx/README.md

* Expanding OpenVX documentation
* Adding HIP Info
* Minor fixes

OpenVX - Documentation

---

MIVisionX-setup.py
README.md

* Setup script with Python 2/3 support
* Supports Linux
+ Ubuntu 18/20
+ CentOS 7/8
+ RedHat 7/8
+ SLES SP2 15

Setup Script - Python3 & Python2 Support

---

amd_openvx_extensions/amd_nn/nn_hip/nn_hip_host_decls.h
amd_openvx_extensions/amd_nn/nn_hip/nn_hip_kernels.cpp
amd_openvx_extensions/amd_nn/src/batch_normalization_layer.cpp
amd_openvx_extensions/amd_nn/src/cast_layer.cpp
amd_openvx_extensions/amd_nn/src/convolution_layer.cpp
amd_openvx_extensions/amd_nn/src/deconvolution_layer.cpp
amd_openvx_extensions/amd_nn/src/fully_connected_layer.cpp
amd_openvx_extensions/amd_nn/src/gather_layer.cpp
amd_openvx_extensions/amd_nn/src/image_tensor_converter.cpp
amd_openvx_extensions/amd_nn/src/kernels.cpp
amd_openvx_extensions/amd_nn/src/kernels.h
amd_openvx_extensions/amd_nn/src/local_response_normalization_layer.cpp
amd_openvx_extensions/amd_nn/src/normalization_layer.cpp
amd_openvx_extensions/amd_nn/src/pooling_layer.cpp
amd_openvx_extensions/amd_nn/src/reshape_layer.cpp
amd_openvx_extensions/amd_nn/src/scale_layer.cpp
amd_openvx_extensions/amd_nn/src/softmax_layer.cpp
amd_openvx_extensions/amd_nn/src/tensor_add.cpp
amd_openvx_extensions/amd_nn/src/tensor_image_converter.cpp
amd_openvx_extensions/amd_nn/src/tensor_matrix_multiply.cpp
amd_openvx_extensions/amd_nn/src/tensor_max.cpp
amd_openvx_extensions/amd_nn/src/tensor_min.cpp
amd_openvx_extensions/amd_nn/src/tensor_multiply.cpp
amd_openvx_extensions/amd_nn/src/tensor_subtract.cpp
amd_openvx_extensions/amd_nn/src/tile_layer.cpp

- This PR adds support for NN layers that call MIOpen. These include convolution, deconvolution, fully_connected, 
local_response_normalization, normalization, pooling, reshape, scale, softmax, tensor_add, tensor_max, tensor_min, tensor_multiply, 
and tensor_subtract layers.
- This PR has partial support for tensor_matrix_multiply. We would need to use rocBLAS for doing GEMM which will be added in the next PR for this layer.

Neural Network Extension, HIP GPU backend - add support for layers that use MIOpen

---

amd_openvx/openvx/ago/ago_platform.cpp
amd_openvx/openvx/openvx.vcxproj
amd_openvx/openvx/openvx.vcxproj.filters

Fix minor issues preventing build on Windows
- use `NULL` instead of undefined `null`
- include `ago\ago_haf_cpu_generic_functions.cpp` in .vcxproj file to compile it

Fix Windows build

---

CMakeLists.txt

This will set dependency to rocm-core package if ROCM_DEP_ROCMCORE
flag is set to ON.

MIVisionX Package -  Set dependency on rocm-core

---

amd_openvx/openvx/ago/ago_interface.cpp
amd_openvx/openvx/ago/ago_internal.h
amd_openvx/openvx/ago/ago_util.cpp
amd_openvx/openvx/api/vx_api.cpp
amd_openvx/openvx/include/vx_ext_amd.h
amd_openvx_extensions/amd_media/encoder.cpp
utilities/loom_io_media/encoder.cpp

this PR also renames the following variables as they are used with both OCL/HIP GPU backends.
amd_kernel_opencl_buffer_update_callback_f to amd_kernel_gpu_buffer_update_callback_f
opencl_buffer_update_param_index to gpu_buffer_update_param_index
AgoKernelOpenclBufferUpdateInfo to AgoKernelGpuBufferUpdateInfo

OpenVX - rename VX_KERNEL_ATTRIBUTE_AMD_OPENCL_BUFFER_UPDATE_CALLBACK to … to VX_KERNEL_ATTRIBUTE_AMD_GPU_BUFFER_UPDATE_CALLBACK

---

amd_openvx_extensions/amd_nn/include/vx_amd_nn.h

Fixes a bug introduced by #732. Noticed by @paveltc and me while testing NN unit tests.
@paveltc Can you try building the C unit tests with this PR and let me know if the enum error goes away

VX_NN - bug fix

---

amd_openvx/openvx/ago/ago_util_opencl.cpp

Added a clWaitForEvents to make sure clEnqueueFillBuffer() is done before executing any other nodes.
This fixes the laplacian pyramid cts failure on Windows.

OpenVX OCL GPU backend - Fix syncing issue

---

amd_openvx_extensions/amd_nn/nn_hip/nn_hip_host_decls.h
amd_openvx_extensions/amd_nn/nn_hip/nn_hip_kernels.cpp
amd_openvx_extensions/amd_nn/src/upsample_nearest_layer.cpp

Implementation of vxUpsampleNearestLayer node on HIP backend which is needed for yolov3 models.

VX_NN - vxUpsampleNearestLayer node implementation on HIP backend

---

amd_openvx/openvx/ago/ago_kernel_api.cpp

Changed the data types of width/height to vx_float32 and then cast to vx_uint32 at the end to avoid warning & floating point exception

OpenVX cts- Floating point exception fix

---

rocAL/rocAL/source/api/rocal_api_data_loaders.cpp

Fixes bug with respect to user given size restricted policy
- Input dimensions given by the user is to be used in case of both ROCAL_USE_USER_GIVEN_SIZE & ROCAL_USE_USER_GIVEN_SIZE_RESTRICTED policies

Fixes bug with respect to user_given_size_restricted decode policy

---

amd_openvx/cmake/FindTurboJpeg.cmake

@srekolam these updates add an ENV Variable - `TURBO_JPEG_PATH` that could be set or pass `TURBO_JPEG_PATH` as a -D cmake build option. Let me know if this would fix SPACK build.

SPACK updates - Turbo JPEG 

---

CMakeLists.txt
amd_openvx/openvx/include/vx_ext_amd.h

OpenVX defines float16 with Experimental flag using hfloat - https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/blob/9b1c5c487722c8f09ab901727def22e78549e0b6/amd_openvx/openvx/include/VX/vx_types.h#L114
To use C++ half.hpp - turn on `AMD_FP16_SUPPORT`

AMD - Float16 Support

---

CHANGELOG.md
README.md
rocAL/rocAL/include/device/device_manager_hip.h

-- rocAL -- Using HIP -- Path:/opt/rocm	Version:5.3.22374	Compiler:clang
Ubuntu 22.04 -- Kapu
* Issue fixed
```
In file included from /home/kiriti/develop/mivisionx-kiriti/MIVisionX/rocAL/rocAL/source/device/device_manager_hip.cpp:27:
/home/kiriti/develop/mivisionx-kiriti/MIVisionX/rocAL/rocAL/./include/device/device_manager_hip.h:56:24: error: ‘shared_ptr’ in namespace ‘std’ does not name a template type
56 | using pRocalHip = std::shared_ptr<DeviceManagerHip>;
```

rocAL - add missing header

---

amd_openvx/openvx/ago/ago_internal.h

Changing max tensor dimensions from 4 to 6.
Needed to support YoloV4 onnx model (through vx_amd_migraphx) which uses 5D output tensor.
Tested with conformance tests and neutral network tests -- Passes both

amd_openvx - increase max tensor dimension

---

CMakeLists.txt
amd_openvx_extensions/amd_custom/custom_lib/CMakeLists.txt
apps/cloud_inference/server_app/CMakeLists.txt
apps/dg_test/CMakeLists.txt
apps/image_augmentation/CMakeLists.txt
apps/mivisionx_openvx_classifier/CMakeLists.txt
model_compiler/python/nnir_to_clib.py

Summary of proposed changes:
- Single version package: add ldconfig, no RPATH/RUNPATH in either binaries or libraries
- Multi version package: use RPATH for binaries, no RPATH/RUNPATH for libraries
- amdclang/clang/hipcc compilers shall not add RPATH/RUNPATH to produced binaries or libraries unless explicitly requested by an option
- Versioning scripts will take care of adding rpath to binaries for multi version package

Remove RPATH/RUNPATH - Adding SKIP RPATH flag

---

CMakeLists.txt
amd_openvx_extensions/amd_custom/custom_lib/CMakeLists.txt
apps/cloud_inference/server_app/CMakeLists.txt
apps/dg_test/CMakeLists.txt
apps/image_augmentation/CMakeLists.txt
apps/mivisionx_openvx_classifier/CMakeLists.txt
model_compiler/python/nnir_to_clib.py

This reverts commit a5a4948f40ef1b50019137d6085e947d06d0d7e7.
As the rpath removal change proposed has been deferred to a later release. It would be worse to
have only some of the libraries changed in ROCm 5.5 than to have them all configured one way or the other, so we will undo the changes made to Mivisionx module for this release.

Revert "Remove RPATH/RUNPATH - Adding SKIP RPATH flag (#995)"

---

MIVisionX-setup.py
README.md
amd_openvx/cmake/FindAMDRPP.cmake

* Support RedHat 7/8/9
* Fix Issues on CentOS 8
* Add support to Install RPP & rocAL on non-Ubuntu based OS

Setup - Support for RedHat and Updates

---

rocAL/rocAL_pybind/amd/rocal/pipeline.py
rocAL/rocAL_pybind/amd/rocal/plugin/generic.py
rocAL/rocAL_pybind/amd/rocal/plugin/tf.py

@paveltc Here is the fix for the one hot error. Added support for numpy/cupy arrays along with torch tensors

rocal_pybind - bug fix for one hot encoded labels

---

CMakeLists.txt

Proposed Changes:
- Cleaning up RPATH removal logic
- This was added as part of Adding SKIP RPATH flag (#995) and Enhanced for BUILD_DEV Option (#1010)
- Since #995 changes are reverted, this change also required to be reverted.

CMakeLists - Avoid RPATH removal from binaries

---

rocAL/rocAL/include/pipeline/image.h
rocAL/rocAL/source/api/rocal_api_augmentation.cpp
rocAL/rocAL/source/augmentations/geometry_augmentations/node_resize.cpp
rocAL/rocAL/source/decoders/image/fused_crop_decoder.cpp
rocAL/rocAL/source/decoders/image/turbo_jpeg_decoder.cpp
rocAL/rocAL/source/loaders/image/image_loader.cpp
rocAL/rocAL/source/loaders/image/image_read_and_decode.cpp
rocAL/rocAL/source/parameters/parameter_rocal_crop.cpp
rocAL/rocAL/source/pipeline/image.cpp
rocAL/rocAL_pybind/amd/rocal/decoders.py

Added changes required for classification training convergence
1. Added patch to compute resize dimensions using original image dimensions instead of decoded dimensions
2. Increased the max aspect ratio used for creating resize output buffer to 6 for accommodating the largest resize dimension in ImageNet validation dataset
3. Changed the DCT algorithm used in TurboJpeg decoder to accurate DCT algorithm which is the default algorithm used in DALI and PIL libraries
4. Added patch for using the correct rounding mode when calculating the crop dimensions
5. Added an else condition to choose another image in the same batch when the image fails decoding using TurboJpeg decoder
6. Changed the random aspect ratio range to the values used in torchvision's RandomResizedCrop function

rocAL - changes for classification training convergence

---

toolkit/amd_data_analysis_toolkit/object_detection/generate-visualization.py
toolkit/amd_data_analysis_toolkit/object_detection/readme.md

Object detection code needed to be updated. Able to run the script now.
```
python generate-visualization.py -i sample/boundingBoxCompare-results.csv -d ../../../data/images/AMD-dataSet-416X416/ -o outputFolder/ -l sample/labels.csv -f objectDetectionVisualized -g sample/groundTruthFile.csv -t sample/boundingBoxToolFile.csv
resultsSummary.txt generation ..
resultsSummary.txt generated
labelSummary.csv generation ..
labelSummary.csv generated
index.html generation ..
results saved in backup drive
index.html generated
```

ADAT - modifying code to support python3

---

MIVisionX-setup.py
README.md

Backend - CPU Deps support

---

.github/dependabot.yml

target develop branch for PRs by dependabot instead of default branch (currently master)
add labels related to Read the Docs
- docs: PRs are related to documentation
- dependencies: PRs are for documentation requirements
- noCI: the CI for Read the Docs are separate from math library CI
add doc team as reviewers for dependabot PRs

Documentation - Update dependabot configurations

---

CHANGELOG.md
MIVisionX-setup.py
README.md
docker/archive/mivisionx-opencl-on-ubuntu20.dockerfile
docker/linux/mivisionx-on-rhel-8.dockerfile
docker/linux/mivisionx-on-rhel-9.dockerfile
docker/linux/mivisionx-on-sles-15.dockerfile
docker/mivisionx-on-ubuntu20.dockerfile
docker/mivisionx-on-ubuntu22.dockerfile
docker/pytorch/mivisionx-with-pytorch-with-mesa.dockerfile
docker/pytorch/mivisionx-with-pytorch.dockerfile
docker/tensorflow/mivisionx-with-tensorflow.dockerfile
docker/ubuntu20/level-5.dockerfile
docker/ubuntu22/level-5.dockerfile
docs/.sphinx/requirements.in
docs/.sphinx/requirements.txt
docs/conf.py
utilities/mv_deploy/mv_compile.cpp

* Documentation Updates
* Setup Updates
* Docker Updates

Version 2.5.0 - Release Update

---

CMakeLists.txt
utilities/mv_deploy/CMakeLists.txt
utilities/runvx/CMakeLists.txt

ASAN package requires address-sanitized libraries and license file
Exclude binaries from ASAN package
BUILD_DEV will be set to OFF via build parameters, so that header files and other files in share/libexec folder will be excluded from ASAN package

SWDEV-351540 - ASAN packaging for MIvisionX

---

amd_openvx_extensions/amd_rpp/include/vx_ext_rpp.h

Fix build issues wrt PR #1141 
- Change the function declaration name from copy and nop to CopybatchPD and NopbatchPD
- Reintroduce the removed function declaration for tensor API and add description for the same

VX_RPP Fix build issues

---

CHANGELOG.md
MIVisionX-setup.py
README.md

Failure on Ubuntu 20.04
```
s.py", line 22, in <module>
import _pytest.outcomes
ModuleNotFoundError: No module named '_pytest.outcomes'
```

rocAL - Setup Updates

---

.readthedocs.yaml

Problem: Read the Docs (RTD) build is breaking when trying to generate Latex PDF
Solution: Disable this to get RTD building again for the develop and master branches
Note: RTD PR builds only make the HTML documentation, which is why they are passing RTD CI

Stop generating PDF on Read the Docs configuration

---

CMakeLists.txt

Added the packages to the dependent list:
half, rpp, rocblas, miopen-hip, migraphx, rocblas-dev/devel, miopen-hip-deve/devel, migraphx-dev/devel

SWDEV-416547 - Set the dependent packages for MIVisionX

---

amd_openvx_extensions/amd_rpp/include/vx_ext_rpp.h

This PR closes out #1146. It also removes all of the warnings generated from Doxygen for vx_ext_rpp.h

Documentation - Doxygen comments added to amd_rpp extensions

---

amd_openvx/openvx/include/VX/vx_api.h
amd_openvx/openvx/include/vx_ext_amd.h
amd_openvx_extensions/amd_custom/include/vx_amd_custom.h
amd_openvx_extensions/amd_nn/include/vx_amd_nn.h
amd_openvx_extensions/amd_opencv/include/vx_ext_opencv.h
amd_openvx_extensions/amd_winml/include/vx_ext_winml.h

MCW formatted code for rocAL which fixed warnings for other extensions. Cherry picking non rocAL/RPP changes to fix warnings,

Documentation - Doxygen warning fixes

---

tests/openvx_api_tests/CMakeLists.txt

Changes Proposed:
- Exclude test files from MIVisionX ASAN package.
- Fix for SWDEV-430827

MIVisionX ASAN - Exclude library_tests from ASAN pkg

---

rocAL/rocAL/CMakeLists.txt

Even for newer gcc and clang versions, the -std=gnu++17 argument must be added for supporting std::filesystem features while compiling. Due to the missed argument, even gcc versions > 9 with std::filesystem added in libstdc++ fails the compilation test and std::experimental::filesystem is used instead.

Std filesystem cmake fix

---

samples/mv_objdetect/CMakeLists.txt

Fix
```
make[2]: *** [CMakeFiles/mvobjdetect.dir/build.make:90: CMakeFiles/mvobjdetect.dir/mvdeploy_api.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /long_pathname_so_that_rpms_can_package_the_debug_info/src/extlibs/MIVisionX/samples/mv_objdetect/mvdeploy/mvobjdetect.cpp:27:
/long_pathname_so_that_rpms_can_package_the_debug_info/src/extlibs/MIVisionX/samples/mv_objdetect/mvdeploy/mvdeploy.h:60:10: fatal error: half/half.hpp: No such file or directory
60 | #include <half/half.hpp>
|          ^~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/mvobjdetect.dir/build.make:76: CMakeFiles/mvobjdetect.dir/mvobjdetect.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:100: CMakeFiles/mvobjdetect.dir/all] Error 2
make: *** [Makefile:91: all] Error 2 …
```

MV_DEPLOY:Find Half - Fix

---

MIVisionX-setup.py
apps/mivisionx_inference_analyzer/mivisionx_inference_analyzer.py
apps/mivisionx_validation_tool/inference_setup.py
apps/mivisionx_validation_tool/inference_viewer.py
model_compiler/python/nnir.py
model_compiler/python/nnir_to_clib.py

Fixed linting issues for pep8 conformance.
https://peps.python.org/pep-0008/#programming-recommendations
- Use is not operator rather than not ... is. While both expressions are functionally identical, the former is more readable and preferred
- Instead of != None use is not None
- Remove trailing semicolons

Linting fixes for PEP-8 conformance.

---

MIVisionX-setup.py
model_compiler/README.md
tests/neural_network_tests/runNeuralNetworkTests.py

ONNX 1.11.0 - failure on Ubuntu 22.04 -- Need to upgrade to 1.12.0
```
error: legacy-install-failure
× Encountered error while trying to install package.
╰─> onnx
note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

NN Inference Setup - Use ONNX 1.12.0

---

amd_openvx_extensions/amd_media/decoder.cpp

The error was most likely triggered when updating FFmpeg version. 
For VAAPI- ffmpeg returns wrong pix_format which was causing failure in swscale.

AMD Media - Fix FFmpeg swscale error when using hwdec for amd_media

---

CHANGELOG.md
MIVisionX-setup.py
README.md
docs/install/installation.rst

MIVisionX Setup - Updates

---

amd_openvx_extensions/amd_rpp/include/internal_rpp.h
amd_openvx_extensions/amd_rpp/source/kernel_rpp.cpp
amd_openvx_extensions/amd_rpp/source/tensor/Spectrogram.cpp

Reverts ROCm/MIVisionX#1347
```
/home/kiriti/develop/mivisionx-kiriti/MIVisionX/amd_openvx_extensions/amd_rpp/source/tensor/Spectrogram.cpp: In function ‘vx_status processSpectrogram(vx_node, _vx_reference* const*, vx_uint32)’:
/home/kiriti/develop/mivisionx-kiriti/MIVisionX/amd_openvx_extensions/amd_rpp/source/tensor/Spectrogram.cpp:138:22: error: ‘rppt_spectrogram_host’ was not declared in this scope; did you mean ‘rppt_spatter_host’?
138 |         rpp_status = rppt_spectrogram_host(data->pSrc, data->pSrcDesc, data->pDst, data->pDstDesc, data->pSrcLength, data->centerWindows, data->reflectPadding,
|                      ^~~~~~~~~~~~~~~~~~~~~
|                      rppt_spatter_host
make[2]: *** [amd_openvx_extensions/amd_rpp/CMakeFiles/vx_rpp.dir/build.make:1532: …
```

Revert "Introduce Audio Layout and fix Spectrogram "

---

.github/CODEOWNERS

Fixes syntax (docs/* to docs/) and adds doc team as owner for RTD config file

Update CODEOWNERS for documentation

---

MIVisionX-setup.py
docs/install/model-compiler-install.rst
model_compiler/README.md
tests/neural_network_tests/runNeuralNetworkTests.py

Since Python 3.12, the `imp` module has been deprecated, which caused the following error when running NN tests:
`
ModuleNotFoundError: No module named 'imp'
`
This PR upgrades the setup script and python test scripts to install the future package version 1.0.0, which is compatible with the latest Python versions.

NN Dependencies - Bump future package from 0.18.2 to 1.0.0

---

CHANGELOG.md

Fixes incorrect changes to the changelog in #1443. See below.
release/rocm-rel-6.2:
https://github.com/ROCm/MIVisionX/blob/25b2c80270f10215719b1896bb4d7b040c2ab528/CMakeLists.txt#L21
release/rocm-rel-6.3:
https://github.com/ROCm/MIVisionX/blob/d2853a4cc0f5cabfff9d183935531be7fd8f2323/CMakeLists.txt#L21

Fix pkg version headings in CHANGELOG.md

---

MIVisionX-setup.py
docs/install/model-compiler-install.rst
model_compiler/README.md
tests/neural_network_tests/runNeuralNetworkTests.py

* future version upgrade to 1.0.0
* Revert future version to 0.18.2 for rpm
* Update runNeuralNetworkTests.py
---------

ROCm 6.3 - Cherry-pick - NN Dependencies - Bump future package from 0.18.2 to 1.0.0 (#1436)

---

amd_openvx/openvx/include/vx_ext_amd.h

Make AgoTargetAffinityInfo similar to the internal structure AgoTargetAffinityInfo_, to avoid issues while assignment.

VX_EXT_AMD - Fix AgoTargetAffinityInfo

---

amd_openvx_extensions/amd_rpp/include/internal_rpp.h
amd_openvx_extensions/amd_rpp/source/kernel_rpp.cpp
amd_openvx_extensions/amd_rpp/source/tensor/Copy.cpp

Existing Copy node only supports f32, f16, u8 and i8. Recently RPP and rocAL introduced support for other integral dtypes so adding changes in Copy node for supporting the new dtypes

VX_RPP - Extending Copy Node for all dtypes

---

amd_openvx_extensions/amd_rpp/CMakeLists.txt

- Include Log1p path in CMakeLists.txt, overwritten due to merge

VX_RPP - Fix merge conflict wrt Log1p

---

docs/index.rst
docs/install/MIVisionX-prerequisites.rst
docs/tutorials/MIVisionX-apps-samples.rst

PR https://github.com/ROCm/MIVisionX/pull/1540 was merged in with broken links. This corrects that. 
However, because this is an extension of the previous PR, I would like the changes in https://github.com/ROCm/MIVisionX/pull/1540 to be re-reviewed also.

Docs - fixed some broken links from the original PR

---

amd_openvx_extensions/amd_rpp/source/tensor/Blur.cpp

RPP PR [#597](https://github.com/ROCm/rpp/pull/597) added an extra parameter to the box filter kernel API. Due to this, MIVISIONX build fails.
This PR adds the parameter for the kernel in Blur.cpp fixing the build failures

Update blur vx_rpp extension
